@url = http://127.0.0.1:3000

###
GET {{url}}

###
GET {{url}}/health

###
GET {{url}}/cache/test_name

###
PUT {{url}}/cache/test_name
Content-Type: application/json

{
  "value": "test value",
  "expiration_datetime": "2024.04.01T12:00:00.000Z"
}

###
DELETE {{url}}/cache/test_name