@url = http://127.0.0.1:3000

###
GET {{url}}/health

###
GET {{url}}/cache/test_name

###
GET {{url}}/cache/keys

###
PUT {{url}}/cache/test_name
Content-Type: application/json

{
  "value": "test value",
  "expiration_datetime": "2024-04-30T12:00:00.000Z"
}

###
DELETE {{url}}/cache/test_name

###
POST {{url}}/lock/locked_resource_name/acquire

###
POST {{url}}/lock/locked_resource_name/release

###
GET {{url}}/lock/locked_resource_name