name: Performance Testing with K6

#on:
#  push:
#    branches:
#      - main
#  pull_request:
#    branches:
#      - main

jobs:
  performance_test:
    runs-on: ubuntu-latest

    container:
      image: loadimpact/k6:latest

    steps:
      - uses: actions/checkout@v2

      # Setup Rust environment
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      # Build your application (if necessary)
      - name: Build
        run: cargo build --release

      # Start the application in the background
      - name: Start App
        run: |
          nohup target/release/your_app &
          sleep 10  # Give it some time to start up

      # Run k6 load test
      - name: Load Test
        run: k6 run /github/workspace/load_test.js