name: Performance Testing with WRK

#on:
#  push:
#    branches:
#      - main
#  pull_request:
#    branches:
#      - main

jobs:
  performance_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Setup Rust environment
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      # Build your application (if necessary)
      - name: Build
        run: cargo build --release

      # Start the application in the background
      - name: Start App
        run: |
          nohup target/release/your_app &
          sleep 10  # Give it some time to start up

      # Install wrk and perform load testing
      - name: Load Test
        run: |
          sudo apt-get install -y wrk
          wrk -t12 -c400 -d60s http://localhost:8080 --rate 1000